@host = http://localhost:4444/me

###
GET {{host}}/
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTVlZDg2MjRiM2JlNjYyZjZkMmNkMCIsImlhdCI6MTYxMjA0OTc5OSwiZXhwIjoxNjEyMTM2MTk5fQ.sOKkISGBhMmrIR4d7cGkrYTNW8fhHym_7TkcjIoLzg8

Content-Type: application/json
